### ISSUE TITLE
Reading CIF file on windows error

### ISSUE THREAD

**Issue by IN-Gamut** [tootea/ase#1]
I run read_cif() on a cif file and the error shows that it fails to parse the cif file on windows. However, on Linux, it works fine.  

And the problem is in this function :

def unread_line(fileobj):
    """Unread the last line read from _fileobj_."""

```
# If previous line ends with CRLF, we have to back up one extra
# character before entering the loop below
if fileobj.tell() > 2:
    fileobj.seek(-2, 1)
    if fileobj.read(2) == '\r\n':
        fileobj.seek(-1, 1)

while True:
    if fileobj.tell() == 0:
        break
    fileobj.seek(-2, 1)
    if fileobj.read(1) in ('\n', '\r'):
        break
```

it seems like this function does not work as expected on windows. Can you help ?

**Comment by tootea** [comment]
Sorry, I have never used ASE on Windows. Additionally, I have not done any ASE development for quite some time now, so this repo is seriously out of date. Upstream ASE development takes place at [https://gitlab.com/ase/ase](https://gitlab.com/ase/ase), perhaps they will be able to help you.
